name: Deploy with Docker

on:
  push:
    branches:
      - master
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Docker Login
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      
    - name: Build Docker Image
      run: |
        docker build -t kenanaljaber/aikiryu-react:latest .
        docker push kenanaljaber/aikiryu-react:latest
      
    - name: SSH into Server and Run Docker Container
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
        script: |
          sudo docker rm image aikiryu-react -f 
          sudo docker pull kenanaljaber/aikiryu-react:latest
          sudo docker run -d --name aikiryu-react -p 3000:3000 kenanaljaber/aikiryu-react:latest
